# Generated by Django 2.2.3 on 2019-07-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0003_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
