# Generated by Django 2.2.3 on 2019-07-17 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0004_partners_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='publish', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
        migrations.RemoveField(
            model_name='partners',
            name='description',
        ),
    ]
