# Generated by Django 2.2.3 on 2019-07-17 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0006_sliders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='sliders',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='sliders',
            name='status',
            field=models.CharField(default='publish', max_length=30),
        ),
        migrations.AddField(
            model_name='sliders',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
