# Generated by Django 2.2.3 on 2019-07-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0007_auto_20190717_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
