# Generated by Django 2.2.3 on 2019-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0009_homeservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='subtitle',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
